import { BoardConfig } from './types/board-config';

export const US_VERSION: BoardConfig = {
  jailScreen: '/warhammer/go-to-jail.png',
  winScreen: '/warhammer/winner.png',
  bankruptScreen: '/warhammer/bankrupt.png',
  politics: [
    '/warhammer/politic-1.png',
    '/warhammer/politic-2.png',
    '/warhammer/politic-3.png',
    '/warhammer/politic-0.png',
    '/warhammer/politic-4.png',
  ],
  chances: [
    'Werde in die Kerkerminen des Imperiums geworfen. Gehe direkt dorthin. Gehe nicht über die Stadttore, ziehe keine $ 200 ein.',
    'Rücke vor bis zum Altdorf Train. Ziehe $ 200 ein, wenn du die Stadttore passierst.',
    'Du wurdest zum Kommandanten der Stadtwache gewählt. Zahle jedem Mitspieler $ 50 als Tribut.',
    'Rücke vor bis zu Altdorf Outskirts. Ziehe $ 200 ein, wenn du die Stadttore passierst.',
    'Deine Schatzkammer wurde geplündert. Ziehe $ 150 aus versteckten Reserven ein.',
    'Zahle eine Abgabe an die Armen des Imperiums in Höhe von $ 15.',
    'Rücke vor bis zur nächsten Train. Ziehe $ 200 ein, wenn du die Stadttore passierst.',
    'Gehe 3 Felder zurück, während ein Goblin-Schamane dich in die Irre führt.',
    'Rücke vor bis zur nächsten Train. Ziehe $ 200 ein, wenn du die Stadttore passierst.',
    'Rücke vor bis zum nächsten Utility. Ziehe $ 200 ein, wenn du die Stadttore passierst.',
    'Mache einen Spaziergang auf der Sylvania Crypts. Ziehe $ 200 ein, wenn du über Los gehst',
    'Unternehme einen Streifzug durch Ulthuan. Ziehe $ 200 ein, wenn du die Stadttore passierst.',
    'Führe Reparaturen an deinem gesamten Besitz durch. Zahle $ 25 für jedes Gehöft und $ 100 für jede Festung.',
  ],
  chests: [
    'Du musst Reparaturen an den Straßen des Imperiums zahlen, $ 40 für jedes Gehöft und $ 115 für jede Festung.',
    'Werde in die Kerkerminen der Skaven geworfen. Begib dich direkt dorthin. Gehe nicht über die Stadtmauer, ziehe keine $ 200 ein.',
    'Du erbst $ 100 aus der Schatztruhe eines gefallenen Adligen.',
    'Aus dem Verkauf von Schmuggelware erhältst du $ 45.',
    'Deine Lebensversicherung wird fällig, nachdem du einen Chaoskrieger besiegt hast. Ziehe $ 100 ein.',
    'Erhalte $ 25 als Bezahlung für einen Dienst am Tempel von Sigmar.',
    'Zahle Schulgebühren an die Akademie der Lichtmagier: $ 150.',
    'Du hast den zweiten Preis in einem Bogenschießturnier gewonnen. Ziehe $ 10 ein.',
    'Opernkarten für das Fest der Alten Götter: Sammle $ 50 von jedem Spieler.',
    'Zahle $ 50 für die Dienste eines Feldchirurgen während der Schlacht.',
    'Krankenhausrechnung für deine verwundeten Soldaten: Zahle $ 100.',
    'Eine Steuererstattung der imperialen Schatzkammer gewährt dir $ 20.',
    'Ein Bankfehler zugunsten deiner Schatzkammer: Ziehe $ 200 ein.',
    'Dein Wintervorrat wird fällig. Ziehe $ 100 ein.',
  ],
  fields: [
    {
      type: 'Go',
      name: 'GO',
    },
    {
      type: 'Site',
      name: 'Drakwald Forest',
      buyingPrice: 60,
      buildingPrice: 50,
      rentPrices: [2, 10, 30, 90, 160, 250],
    },
    {
      type: 'CommunityChest',
      name: 'Community Chest',
    },
    {
      type: 'Site',
      name: 'Hel Fenn',
      buyingPrice: 60,
      buildingPrice: 50,
      rentPrices: [4, 20, 60, 180, 320, 450],
    },
    {
      type: 'Tax',
      name: 'Income Tax',
      amount: 200,
    },
    {
      type: 'Station',
      name: 'Altdorf Train',
      rentPrices: [25, 50, 100, 200],
      buyingPrice: 100,
    },
    {
      type: 'Site',
      name: 'Altdorf Outskirts',
      buyingPrice: 100,
      buildingPrice: 50,
      rentPrices: [6, 30, 90, 270, 400, 550],
    },
    {
      type: 'Chance',
      name: 'Chance',
    },
    {
      type: 'Site',
      name: 'Carroburg Docks',
      buyingPrice: 100,
      buildingPrice: 50,
      rentPrices: [6, 30, 90, 270, 400, 550],
    },
    {
      type: 'Site',
      name: 'Reikland Hills',
      buyingPrice: 120,
      buildingPrice: 50,
      rentPrices: [8, 40, 100, 300, 450, 600],
    },
    {
      type: 'Jail',
      name: 'Jail',
    },
    {
      type: 'Site',
      name: 'Middenheim Gate',
      buyingPrice: 140,
      buildingPrice: 100,
      rentPrices: [10, 50, 150, 450, 625, 750],
    },
    {
      type: 'Utility',
      name: 'Dwarfen Jewerly Forges',
      buyingPrice: 100,
    },
    {
      type: 'Site',
      name: 'Nuln Foundry',
      buyingPrice: 140,
      buildingPrice: 100,
      rentPrices: [10, 50, 150, 450, 625, 750],
    },
    {
      type: 'Site',
      name: 'Averheim Market',
      buyingPrice: 160,
      buildingPrice: 100,
      rentPrices: [12, 60, 180, 500, 700, 900],
    },
    {
      type: 'Station',
      name: 'Kislev Train',
      rentPrices: [25, 50, 100, 200],
      buyingPrice: 100,
    },
    {
      type: 'Site',
      name: 'Marienburg Wharf',
      buyingPrice: 180,
      buildingPrice: 100,
      rentPrices: [14, 70, 200, 550, 750, 950],
    },
    {
      type: 'CommunityChest',
      name: 'Community Chest',
    },
    {
      type: 'Site',
      name: 'Blackfire Pass',
      buyingPrice: 180,
      buildingPrice: 100,
      rentPrices: [14, 70, 200, 550, 750, 950],
    },
    {
      type: 'Site',
      name: 'Talabheim Road',
      buyingPrice: 200,
      buildingPrice: 100,
      rentPrices: [16, 80, 220, 600, 800, 1000],
    },
    {
      type: 'FreeParking',
      name: 'Free Parking',
    },
    {
      type: 'Site',
      name: 'Sylvania Crypts',
      buyingPrice: 220,
      buildingPrice: 150,
      rentPrices: [18, 90, 250, 700, 875, 1050],
    },
    {
      type: 'Chance',
      name: 'Chance',
    },
    {
      type: 'Site',
      name: 'Templehof Ruins',
      buyingPrice: 220,
      buildingPrice: 150,
      rentPrices: [18, 90, 250, 700, 875, 1050],
    },
    {
      type: 'Site',
      name: 'Drakenhof Castle',
      buyingPrice: 240,
      buildingPrice: 150,
      rentPrices: [20, 100, 300, 750, 925, 1100],
    },
    {
      type: 'Station',
      name: 'Northern Warmammoths',
      rentPrices: [25, 50, 100, 200],
      buyingPrice: 100,
    },
    {
      type: 'Site',
      name: "Morrslieb's Rise",
      buyingPrice: 260,
      buildingPrice: 150,
      rentPrices: [22, 110, 330, 800, 975, 1150],
    },
    {
      type: 'Site',
      name: 'Grimhold Mines',
      buyingPrice: 260,
      buildingPrice: 150,
      rentPrices: [22, 110, 330, 800, 975, 1150],
    },
    {
      type: 'Utility',
      name: 'Imperial Brewery',
      buyingPrice: 100,
    },
    {
      type: 'Site',
      name: 'Ekrund Hold',
      buyingPrice: 280,
      buildingPrice: 150,
      rentPrices: [24, 120, 360, 850, 1025, 1200],
    },
    {
      type: 'GoToJail',
      name: 'Go To Jail',
    },
    {
      type: 'Site',
      name: 'Karak Kadrin',
      buyingPrice: 300,
      buildingPrice: 200,
      rentPrices: [26, 130, 390, 900, 1100, 1275],
    },
    {
      type: 'Site',
      name: 'Karak Eight Peaks',
      buyingPrice: 300,
      buildingPrice: 200,
      rentPrices: [26, 130, 390, 900, 1100, 1275],
    },
    {
      type: 'CommunityChest',
      name: 'Community Chest',
    },
    {
      type: 'Site',
      name: 'Zharr Naggrund',
      buyingPrice: 320,
      buildingPrice: 200,
      rentPrices: [28, 150, 450, 1000, 1200, 1400],
    },
    {
      type: 'Station',
      name: 'Dwarven Tunnels',
      rentPrices: [25, 50, 100, 200],
      buyingPrice: 100,
    },
    {
      type: 'Chance',
      name: 'Chance',
    },
    {
      type: 'Site',
      name: 'Naggarond',
      buyingPrice: 350,
      buildingPrice: 200,
      rentPrices: [35, 175, 500, 1100, 1300, 1500],
    },
    {
      type: 'Tax',
      name: 'Luxury Tax',
      amount: 75,
    },
    {
      type: 'Site',
      name: 'Ulthuan',
      buyingPrice: 400,
      buildingPrice: 200,
      rentPrices: [50, 200, 600, 1400, 1700, 2000],
    },
  ],
};
